[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "saur_client"
version = "0.1.3"
description = "Client Python pour interagir avec le distributeur SAUR (saur.fr)"
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" } 
authors = [
    { name = "Cekage Dave", email = "github@cekage.net" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "License :: OSI Approved :: MIT License",  
    "Operating System :: OS Independent",
]
dependencies = [
    "aiohttp",
]

[project.urls]
Homepage = "https://github.com/cekage/Saur_fr_client"
Issues = "http://github.com/cekage/Saur_fr_client/issues"
Repository = "https://github.com/cekage/Saur_fr_client.git"

[tool.setuptools.packages.find]
where = ["."]
