# file generated by setuptools_scm
# don't change, don't track in version control

VERSION_TUPLE = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE

__version__ = version = "0.2.4.dev1+unknown"
__version_tuple__ = version_tuple = (0, 2, 4, "dev1", "unknown")
